spring.application.name=daimler-ar-wiring-harness
server.port=8080

aws.region=${AWS_REGION:us-east-1}
aws.accessKeyId=${AWS_ACCESS_KEY_ID:AKIAIOSFODNN7EXAMPLE}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}

aws.s3.bucket=${AWS_S3_BUCKET:daimler-harness-cdn-dev}

app.use-s3=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.com.harness=DEBUG
